// <auto-generated />
using Doorman.Master.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Doorman.Master.Migrations
{
    [DbContext(typeof(DoormanContext))]
    [Migration("20180323210733_AddRoomAccessToken")]
    partial class AddRoomAccessToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Doorman.Master.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessToken");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Doorman.Master.Entities.RoomOccupancySnapshot", b =>
                {
                    b.Property<int>("RoomOccupancySnapshotId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<int>("RoomId");

                    b.HasKey("RoomOccupancySnapshotId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomOccupancySnapshots");
                });

            modelBuilder.Entity("Doorman.Master.Entities.RoomOccupancySnapshot", b =>
                {
                    b.HasOne("Doorman.Master.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
