// <auto-generated />
using DoormanAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DoormanAPI.Migrations
{
    [DbContext(typeof(DoormanContext))]
    partial class DoormanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoormanAPI.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DoormanAPI.Entities.RoomOccupancySnapshot", b =>
                {
                    b.Property<int>("RoomOccupancySnapshotId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<int>("RoomId");

                    b.HasKey("RoomOccupancySnapshotId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomOccupancySnapshots");
                });

            modelBuilder.Entity("DoormanAPI.Entities.RoomOccupancySnapshot", b =>
                {
                    b.HasOne("DoormanAPI.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
